// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBQd_-sSwfCVY2yq4aBXpMv1quKUkrh2U',
    appId: '1:159991275990:web:d8643ce808732e6ca48477',
    messagingSenderId: '159991275990',
    projectId: 'pinjamalat-smk4',
    authDomain: 'pinjamalat-smk4.firebaseapp.com',
    storageBucket: 'pinjamalat-smk4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACGV9Xq35BTwe_1eCDWgZCY8x97vFEz3U',
    appId: '1:159991275990:android:a37d109e65784d10a48477',
    messagingSenderId: '159991275990',
    projectId: 'pinjamalat-smk4',
    storageBucket: 'pinjamalat-smk4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7yoYFtqticIbM1X2o2cDEIAaSHYiR1w',
    appId: '1:159991275990:ios:c1c084e4cde38c60a48477',
    messagingSenderId: '159991275990',
    projectId: 'pinjamalat-smk4',
    storageBucket: 'pinjamalat-smk4.firebasestorage.app',
    iosBundleId: 'com.example.broadcastRentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG7yoYFtqticIbM1X2o2cDEIAaSHYiR1w',
    appId: '1:159991275990:ios:c1c084e4cde38c60a48477',
    messagingSenderId: '159991275990',
    projectId: 'pinjamalat-smk4',
    storageBucket: 'pinjamalat-smk4.firebasestorage.app',
    iosBundleId: 'com.example.broadcastRentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBQd_-sSwfCVY2yq4aBXpMv1quKUkrh2U',
    appId: '1:159991275990:web:c643dc370544be0aa48477',
    messagingSenderId: '159991275990',
    projectId: 'pinjamalat-smk4',
    authDomain: 'pinjamalat-smk4.firebaseapp.com',
    storageBucket: 'pinjamalat-smk4.firebasestorage.app',
  );
}
